server:
  port: 8080

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
jwt:
  secret: ChangeThisSecretToAStrongOne1234
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.commerce.auth.controller

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
  instance:
    hostname: auth-service
    prefer-ip-address: false