server:
  port: 8761  #default port that service registry runs on

spring:
  application:
    name: service-registry

eureka:
  instance:
    hostname: service-registry  # Changed from localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka